# Generated by Django 6.0.2 on 2026-03-01 18:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='restaurant name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('cuisine_type', models.CharField(choices=[('ITALIAN', 'Italian'), ('CHINESE', 'Chinese'), ('INDIAN', 'Indian'), ('JAPANESE', 'Japanese'), ('MEXICAN', 'Mexican'), ('THAI', 'Thai'), ('FRENCH', 'French'), ('AMERICAN', 'American'), ('MEDITERRANEAN', 'Mediterranean'), ('VEGETARIAN', 'Vegetarian'), ('VEGAN', 'Vegan'), ('SEAFOOD', 'Seafood'), ('STEAKHOUSE', 'Steakhouse'), ('BBQ', 'BBQ'), ('BAKERY', 'Bakery'), ('CAFE', 'Cafe'), ('FAST_FOOD', 'Fast Food'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20, verbose_name='cuisine type')),
                ('price_level', models.CharField(choices=[('$', 'Budget - Under $15'), ('$$', 'Moderate - $15-$30'), ('$$$', 'Expensive - $30-$50'), ('$$$$', 'Luxury - Over $50')], default='$$', max_length=4, verbose_name='price level')),
                ('logo', models.URLField(blank=True, max_length=500, verbose_name='logo URL')),
                ('cover_image', models.URLField(blank=True, max_length=500, verbose_name='cover image URL')),
                ('gallery', models.JSONField(blank=True, default=list, verbose_name='gallery')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='contact email')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='contact phone')),
                ('website', models.URLField(blank=True, max_length=500, verbose_name='website')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='state')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='country')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='postal code')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('business_hours', models.JSONField(default=dict, help_text='Business hours in JSON format: {"monday": {"open": "09:00", "close": "22:00", "closed": false}}', verbose_name='business hours')),
                ('features', models.JSONField(default=list, help_text='Restaurant features like "parking", "wifi", "outdoor_seating", etc.', verbose_name='features')),
                ('dietary_options', models.JSONField(default=list, help_text='Dietary options like "vegetarian", "vegan", "gluten_free", etc.', verbose_name='dietary options')),
                ('total_branches', models.PositiveIntegerField(default=0, verbose_name='total branches')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='average rating')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name='total reviews')),
                ('total_bookings', models.PositiveIntegerField(default=0, verbose_name='total bookings')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='meta title')),
                ('meta_description', models.TextField(blank=True, verbose_name='meta description')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, verbose_name='meta keywords')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_restaurants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'restaurant',
                'verbose_name_plural': 'restaurants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='item name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('category', models.CharField(choices=[('APPETIZER', 'Appetizer'), ('MAIN_COURSE', 'Main Course'), ('SOUP', 'Soup'), ('SALAD', 'Salad'), ('SEAFOOD', 'Seafood'), ('PASTA', 'Pasta'), ('PIZZA', 'Pizza'), ('BURGER', 'Burger'), ('SANDWICH', 'Sandwich'), ('DESSERT', 'Dessert'), ('BEVERAGE', 'Beverage'), ('ALCOHOL', 'Alcoholic Beverage'), ('SIDE', 'Side Dish'), ('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch Special'), ('DINNER', 'Dinner Special'), ('COMBO', 'Combo Meal'), ('KIDS', "Kids' Menu")], db_index=True, max_length=20, verbose_name='category')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='discount price')),
                ('dietary_types', models.JSONField(blank=True, default=list, verbose_name='dietary types')),
                ('spice_level', models.CharField(choices=[('MILD', 'Mild'), ('MEDIUM', 'Medium'), ('HOT', 'Hot'), ('EXTRA_HOT', 'Extra Hot')], default='MILD', max_length=10, verbose_name='spice level')),
                ('calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='calories')),
                ('preparation_time', models.PositiveSmallIntegerField(default=15, verbose_name='preparation time (minutes)')),
                ('image', models.URLField(blank=True, max_length=500, verbose_name='image URL')),
                ('is_available', models.BooleanField(db_index=True, default=True, verbose_name='available')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('is_popular', models.BooleanField(default=False, verbose_name='popular')),
                ('includes', models.JSONField(blank=True, default=list, verbose_name='includes')),
                ('allergens', models.JSONField(blank=True, default=list, verbose_name='allergens')),
                ('customization_options', models.JSONField(blank=True, default=dict, verbose_name='customization options')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='tags')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='total orders')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='average rating')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'menu item',
                'verbose_name_plural': 'menu items',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='branch name')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='branch code')),
                ('address', models.TextField(verbose_name='address')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='city')),
                ('state', models.CharField(max_length=100, verbose_name='state')),
                ('country', models.CharField(max_length=100, verbose_name='country')),
                ('postal_code', models.CharField(max_length=20, verbose_name='postal code')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('business_hours', models.JSONField(default=dict, help_text='Branch-specific business hours (overrides restaurant hours)', verbose_name='business hours')),
                ('total_tables', models.PositiveIntegerField(default=0, verbose_name='total tables')),
                ('total_seats', models.PositiveIntegerField(default=0, verbose_name='total seats')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('RENOVATING', 'Renovating'), ('TEMPORARILY_CLOSED', 'Temporarily Closed')], db_index=True, default='OPEN', max_length=20, verbose_name='status')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='branch images')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'branch',
                'verbose_name_plural': 'branches',
                'ordering': ['restaurant__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_number', models.CharField(db_index=True, max_length=10, verbose_name='table number')),
                ('seat_type', models.CharField(choices=[('W', 'Window'), ('C', 'Corner'), ('NORMAL', 'Normal'), ('PRIVATE', 'Private'), ('OUTDOOR', 'Outdoor'), ('BAR', 'Bar')], db_index=True, default='NORMAL', max_length=10, verbose_name='seat type')),
                ('capacity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='capacity')),
                ('minimum_spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='minimum spend')),
                ('is_accessible', models.BooleanField(default=False, verbose_name='wheelchair accessible')),
                ('is_private', models.BooleanField(default=False, verbose_name='private')),
                ('has_outlet', models.BooleanField(default=False, verbose_name='has electrical outlet')),
                ('has_view', models.BooleanField(default=False, verbose_name='has view')),
                ('floor', models.CharField(blank=True, max_length=20, verbose_name='floor')),
                ('section', models.CharField(blank=True, max_length=50, verbose_name='section')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Under Maintenance')], db_index=True, default='AVAILABLE', max_length=20, verbose_name='status')),
                ('is_reserved', models.BooleanField(db_index=True, default=False, verbose_name='is reserved')),
                ('qr_code', models.URLField(blank=True, max_length=500, verbose_name='QR code URL')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurants.branch')),
            ],
            options={
                'verbose_name': 'table',
                'verbose_name_plural': 'tables',
                'ordering': ['branch', 'table_number'],
            },
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['name', 'city'], name='restaurants_name_4a96af_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['cuisine_type', 'city'], name='restaurants_cuisine_0f2c14_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['average_rating', '-total_bookings'], name='restaurants_average_ff6662_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['is_active', 'is_verified'], name='restaurants_is_acti_596eec_idx'),
        ),
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.CheckConstraint(condition=models.Q(('average_rating__gte', 0), ('average_rating__lte', 5)), name='valid_average_rating'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['restaurant', 'category'], name='restaurants_restaur_741f8f_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['restaurant', 'is_available'], name='restaurants_restaur_1087ee_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['restaurant', 'is_featured'], name='restaurants_restaur_4a0dfc_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['price'], name='restaurants_price_ffdceb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('restaurant', 'name', 'category')},
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['restaurant', 'city'], name='restaurants_restaur_af152a_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['code'], name='restaurants_code_d81951_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['status'], name='restaurants_status_e8e46e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('restaurant', 'code')},
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['branch', 'status'], name='restaurants_branch__3da4b6_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['branch', 'seat_type'], name='restaurants_branch__da780e_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['branch', 'capacity'], name='restaurants_branch__925cce_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['is_reserved'], name='restaurants_is_rese_15ab40_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('branch', 'table_number')},
        ),
    ]
