# Generated by Django 6.0.2 on 2026-03-01 18:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_id', models.CharField(db_index=True, editable=False, help_text='Format: RSX-YYYY-000001', max_length=20, unique=True, verbose_name='booking ID')),
                ('date', models.DateField(db_index=True, verbose_name='booking date')),
                ('start_time', models.TimeField(db_index=True, verbose_name='start time')),
                ('end_time', models.TimeField(db_index=True, verbose_name='end time')),
                ('duration', models.PositiveSmallIntegerField(help_text='Booking duration in hours (1-2)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='duration (hours)')),
                ('total_guests', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='total guests')),
                ('special_requests', models.TextField(blank=True, verbose_name='special requests')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='total price')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='deposit amount')),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('COMPLETED', 'Completed')], db_index=True, default='PENDING_PAYMENT', max_length=20, verbose_name='status')),
                ('waiter_name', models.CharField(blank=True, max_length=255, verbose_name='waiter name')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmed at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='restaurants.branch')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='restaurants.restaurant')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='restaurants.table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'bookings',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('COMPLETED', 'Completed')], max_length=20, verbose_name='old status')),
                ('new_status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('COMPLETED', 'Completed')], max_length=20, verbose_name='new status')),
                ('changed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='changed at')),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='bookings.booking')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'booking history',
                'verbose_name_plural': 'booking histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingMenu',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price at the time of booking', max_digits=10, verbose_name='unit price')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='subtotal')),
                ('special_instructions', models.TextField(blank=True, verbose_name='special instructions')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='bookings.booking')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_menus', to='restaurants.menuitem')),
            ],
            options={
                'verbose_name': 'booking menu item',
                'verbose_name_plural': 'booking menu items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('CONFIRMATION', 'Booking Confirmation'), ('REMINDER', 'Booking Reminder'), ('CANCELLATION', 'Booking Cancellation'), ('REJECTION', 'Booking Rejection'), ('EXPIRY', 'Booking Expiry'), ('COMPLETION', 'Booking Completion')], db_index=True, max_length=20, verbose_name='notification type')),
                ('sent_to', models.EmailField(max_length=254, verbose_name='sent to')),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='sent at')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('body', models.TextField(verbose_name='body')),
                ('is_successful', models.BooleanField(default=True, verbose_name='is successful')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'booking notification',
                'verbose_name_plural': 'booking notifications',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_id'], name='bookings_bo_booking_eb8fc3_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='bookings_bo_user_id_69a5d5_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['restaurant', 'date'], name='bookings_bo_restaur_640b07_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['branch', 'date', 'status'], name='bookings_bo_branch__37adae_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['table', 'date', 'start_time'], name='bookings_bo_table_i_99c094_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'expires_at'], name='bookings_bo_status_86acff_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('duration__gte', 1), ('duration__lte', 2)), name='valid_duration'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('total_guests__gte', 1), ('total_guests__lte', 20)), name='valid_total_guests'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['CANCELLED', 'REJECTED', 'EXPIRED']), _negated=True), fields=('table', 'date', 'start_time'), name='unique_active_booking_per_table'),
        ),
        migrations.AddIndex(
            model_name='bookinghistory',
            index=models.Index(fields=['booking', 'changed_at'], name='bookings_bo_booking_875e36_idx'),
        ),
        migrations.AddIndex(
            model_name='bookinghistory',
            index=models.Index(fields=['new_status', 'changed_at'], name='bookings_bo_new_sta_e3c5d5_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingmenu',
            index=models.Index(fields=['booking', 'menu_item'], name='bookings_bo_booking_8dd147_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingmenu',
            unique_together={('booking', 'menu_item')},
        ),
        migrations.AddIndex(
            model_name='bookingnotification',
            index=models.Index(fields=['booking', 'notification_type'], name='bookings_bo_booking_af6435_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingnotification',
            index=models.Index(fields=['sent_at', 'is_successful'], name='bookings_bo_sent_at_69a209_idx'),
        ),
    ]
